version: "3"

services:
  amplify:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - ~/.aws/:/root/.aws/
    ports:
      - "3000:3000"
    tty: true
